{{- if $.Values.global.pgpKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ploigos-workflow.pgpKeysSecretName" . }}
  labels:
    {{- include "ploigos-workflow.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- with $.Values.global.pgpKeys }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
